In [ ]:
import numpy as np;
#引入numpy包并命名别名np

In [ ]:
#创建数组
a = np.array([1,2,3,4,5]);
print(a);

[1 2 3 4 5]


In [ ]:
#返回一个等差数列的数组 不包含结尾
getrarnge = np.arange(1,10,2);
print(getrarnge);

[1 3 5 7 9]


In [6]:
#创建全零数组
np.zeros(5);
print(np.zeros(5));

[0. 0. 0. 0. 0.]


In [7]:
#创建全一数组
np.ones(5);
print(np.ones(5));

[1. 1. 1. 1. 1.]


In [ ]:
#改变数组的形状 确保数组的元素个数不变，改变数组的形状
b = np.array([[1,2,3],[4,5,6]]);
resArr = b.reshape(3,2);
print(resArr);

[[1 2]
 [3 4]
 [5 6]]


In [12]:
#置换数组行列
c = np.array([[1, 2], [3, 4]])
resArr1 = c.T;
print(resArr1);

[[1 3]
 [2 4]]


In [ ]:
#置换数组行列
arr = np.array([[1, 2], [3, 4]])
print(arr)
transposed_arr = np.transpose(arr)
print(transposed_arr)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [16]:
#点积 @ 或者 np.dot
#两个数组的点积是通过将第一个数组的行与第二个数组的列对应元素相乘获得的
#向量的点积返回一个标量
#矩阵的点积返回一个矩阵
#矩阵的点积必须是第一个矩阵的列数等于第二个矩阵的行数 否则会报错
#点积的结果是第一个矩阵的行数和第二个矩阵的列数 
#运算过程是第一个矩阵的行与第二个矩阵的列对应元素相乘然后相加

#点积 矩阵
a = np.array([[1,2],[3,4]]);
b = np.array([[5,6],[7,8]]);
print(a@b);

#两个向量的点积
c = np.array([1,2]);
d = np.array([3,4]);
print(c@d);

#矩阵与向量的点积返回一个向量
e = np.array([[1,2],[3,4]]);
f = np.array([5,6]);
print(e@f);

#向量与标量的乘积
g = np.array([1,2]);
print(g*2);


[[19 22]
 [43 50]]
11
[17 39]
[2 4]


In [ ]:

#数组的加法
a = np.array([1,2,3]);
b = np.array([4,5,6]);
print(a+b);

[5 7 9]


In [18]:
#数组的值获取
a = np.array([1,2,3]);
print(a[0]);
#获取最后一个值
print(a[-1]);
#获取从下标0开始到下标2的值
print(a[0:2]);
print(a[:2]);
print(a[0:]);

1
3
[1 2]
[1 2]
[1 2 3]


In [19]:
#数组求和
a = np.array([1,2,3]);
print(a.sum());

6


In [20]:
#计算均值
a = np.array([1,2,3]);
print(a.mean());

2.0


In [22]:
#获取数组最大值最小值与最大值最小值的索引
a = np.array([1,2,3]);
print(a.max());
print(a.min());
print(a.argmax());
print(a.argmin());

3
1
2
0


In [23]:
#数组排序
a = np.array([3,2,1]);
print(np.sort(a));

[1 2 3]


In [24]:
#引入torch包
import torch;
#创建一个张量
a = torch.tensor([1,2,3]);
print(a);

tensor([1, 2, 3])


In [ ]:
#明天再写张量的操作