In [ ]:
#引入torch
import torch;
#创建张量 张量作为容器
x = torch.tensor([1,2,3,4]);
#打印张量
print(x);

tensor([1, 2, 3, 4])


In [2]:
#创建一个全是0的张量
x = torch.zeros(2,3);
print(x);

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [3]:
#创建一个全是1的张量
x = torch.ones(2,3);
print(x);

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [8]:
#创建一个随机张量
x = torch.rand(2,3)*10;
print(x);

tensor([[0.7633, 2.0736, 0.7605],
        [7.8881, 8.0691, 7.9623]])


In [9]:
#随机一个正态分布的张量
x = torch.randn(2,3);
print(x);

tensor([[-0.6462,  0.2620, -0.8428],
        [ 1.1195, -0.8046, -0.6330]])


In [ ]:
#张量的运算
x = torch.tensor([1,2,3,4]);
y = torch.tensor([2,2,2,2]);
print(x+y);
print(x-y);
print(x*y);#乘积 矩阵对应相乘
print(x/y);


tensor([3, 4, 5, 6])
tensor([-1,  0,  1,  2])
tensor([2, 4, 6, 8])
tensor([0.5000, 1.0000, 1.5000, 2.0000])


In [11]:
#张量的运算符
x = torch.tensor([1,2,3,4]);
y = torch.tensor([2,2,2,2]);
print(x.add(y));
print(x.sub(y));
print(x.mul(y));
print(x.div(y));

tensor([3, 4, 5, 6])
tensor([-1,  0,  1,  2])
tensor([2, 4, 6, 8])
tensor([0.5000, 1.0000, 1.5000, 2.0000])


In [13]:
#张量的运算符
x = torch.tensor([1,2,3,4]);
y = torch.tensor([2,2,2,2]);
print(torch.add(y,x));
print(torch.sub(y,x));
print(torch.mul(y,x));
print(torch.div(y,x));

tensor([3, 4, 5, 6])
tensor([ 1,  0, -1, -2])
tensor([2, 4, 6, 8])
tensor([2.0000, 1.0000, 0.6667, 0.5000])


In [ ]:
#张量的向量点积
x = torch.tensor([1,2,3,4]);
y = torch.tensor([2,2,2,2]);
print(x.dot(y));

tensor(20)


In [ ]:
#张量的矩阵点积能使用dot吗 不行 会报错 不像numpy 通用@符号
#x = torch.tensor([[1,2],[3,4]]);
#y = torch.tensor([[2,2],[2,2]]);
#print(x.dot(y));
x = torch.tensor([[1,2],[3,4]]);
y = torch.tensor([[2,2],[2,2]]);
#print(torth.dot(y,x));#或者使用y.mm(x)  y@x
print(y.mm(x));
print(y@x); #也可以使用numpy中的矩阵点积符号
print(torch.mm(y,x));

tensor([[ 8, 12],
        [ 8, 12]])
tensor([[ 8, 12],
        [ 8, 12]])
tensor([[ 8, 12],
        [ 8, 12]])


In [22]:
#矩阵点积
x = torch.tensor([[1,2],[3,4]]);
y = torch.tensor([[2,2],[2,2]]);
print(x.matmul(y));
print(torch.mm(x,y));
print(x@y);

tensor([[ 6,  6],
        [14, 14]])
tensor([[ 6,  6],
        [14, 14]])
tensor([[ 6,  6],
        [14, 14]])


In [ ]:
#改变张量的形状
x = torch.tensor([[1,2,3],[4,5,6]]);
print(x);
print(x.shape);
print(x.size());
print(x.view(3,2));
print(x.view(6,1));
print(x.view(6));
print(x.view(-1,2));
print(x.view(-1,3));#-1表示自动计算
print(x.view(3,-1));#-1表示自动计算
#设置一个不能平均的形状
try: #捕获异常
    print(x.view(4,-1));
except Exception as e:
    print(e);

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
torch.Size([2, 3])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
shape '[4, -1]' is invalid for input of size 6


In [ ]:
#置换张量
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]]);
print(x);
#print(x.t());#置换维度 行列互换
print(x.transpose(0,1));#置换维度
print(x.transpose(1,0));#置换维度
#print(x.permute(0,2));#置换维度设置为2报错
print(x.permute(1,0));#置换维度

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [ ]:
#展平为一维数组
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]]);
print(x);
print(x.flatten());
print(x.view(-1));#展平为一维数组

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [30]:
#张量索引切片
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]]);
print(x);
print(x[0]);
print(x[0][0]);
print(x[0,0]);
print(x[0,:]);#取第一行
print(x[:,0]);#取第一列
print(x[0:2]);#取前两行
print(x[0:2,0:2]);#取前两行前两列
print(x[0:2,:]);#取前两行
print(x[:,0:2]);#取前两列
print(x[0:2,0]);#取前两行第一列

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)
tensor(1)
tensor([1, 2, 3])
tensor([1, 4, 7])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2],
        [4, 5]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2],
        [4, 5],
        [7, 8]])
tensor([1, 4])


In [ ]:
#torch.gather()函数
x = torch.tensor([[1,2],[3,4],[5,6]]);
print(x);
y = torch.tensor([[0,0],[1,0],[0,1]]);
print(y);
print(torch.gather(x,1,y));#按照y的索引取x的值
#解释一下 就是y的下标加上y的值 比如y的下标是0 y的下标对应的值是0 所以是[0,0] x的值是1
#y的下标是0 y的下标对应的第二个值是0 所以是[0,0] x的值是1 
#结合上面的是[[0,0],[0,0]] = 对应的x的值得出是[[1,1]]
#x = [[1,2],[3,4],[5,6]]
#y = [[0,0],[1,0],[0,1]]
#取x的值
#x[0][0] x[0][0]
#x[1][0] x[1][0]
#x[2][0] x[2][1]

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[0, 0],
        [1, 0],
        [0, 1]])
tensor([[1, 1],
        [4, 3],
        [5, 6]])
